In [1]:
import numpy as np

In [2]:
from numpy import genfromtxt
data = genfromtxt('D:/Data Science Bootcamp/Deep Learning/Session 02/bank_note_data.txt', delimiter=',')

In [3]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
labels = data[:,4]
labels

array([0., 0., 0., ..., 1., 1., 1.])

0 real 1 fake

In [5]:
features = data[:,0:4]
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [6]:
X = features
y = labels

Train Test Split

In [7]:
from sklearn.model_selection import train_test_split

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [33]:
X_train

array([[-1.3885  , 12.5026  ,  0.69118 , -7.5487  ],
       [ 2.7744  ,  6.8576  , -1.0671  ,  0.075416],
       [-4.2887  , -7.8633  , 11.8387  , -1.8978  ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [34]:
X_test

array([[ 1.5691  ,  6.3465  , -0.1828  , -2.4099  ],
       [-0.27802 ,  8.1881  , -3.1338  , -2.5276  ],
       [ 0.051979,  7.0521  , -2.0541  , -3.1508  ],
       ...,
       [ 3.4626  , -4.449   ,  3.5427  ,  0.15429 ],
       [-0.278   ,  8.1881  , -3.1338  , -2.5276  ],
       [ 2.7831  , 10.9796  , -3.557   , -4.4039  ]])

In [35]:
y_test

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1.,
       1., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0.,
       0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1.,
       1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       1., 1., 0., 1., 0.

Standardizing the Data

In [36]:
from sklearn.preprocessing import MinMaxScaler

In [37]:
scaler_object = MinMaxScaler()

In [38]:
scaler_object.fit(X_train)

MinMaxScaler()

In [39]:
scaled_X_train = scaler_object.transform(X_train)

In [40]:
scaled_X_test = scaler_object.transform(X_test)

In [41]:
scaled_X_train

array([[4.07704678e-01, 9.83199063e-01, 2.56697443e-01, 9.33178971e-02],
       [7.07908761e-01, 7.71971248e-01, 1.80872580e-01, 8.05140280e-01],
       [1.98559159e-01, 2.21136252e-01, 7.37428144e-01, 6.20911798e-01],
       ...,
       [4.11050776e-04, 8.63104170e-01, 2.34046756e-01, 3.74261253e-01],
       [2.58284115e-01, 6.16029366e-01, 2.33861752e-01, 7.02643151e-01],
       [2.65661395e-01, 2.44444278e-01, 7.20316361e-01, 7.44775785e-01]])

In [42]:
X_train

array([[-1.3885  , 12.5026  ,  0.69118 , -7.5487  ],
       [ 2.7744  ,  6.8576  , -1.0671  ,  0.075416],
       [-4.2887  , -7.8633  , 11.8387  , -1.8978  ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

Building the Model

In [43]:
from keras.models import Sequential
from keras.layers import Dense

In [44]:
#initiating model
model = Sequential()

model.add(Dense(4, input_dim=4, activation='relu'))

model.add(Dense(8, activation='relu'))

model.add(Dense(1, activation='sigmoid'))

Compile Model

In [45]:
model.compile(loss="binary_crossentropy", optimizer='adam', metrics=['accuracy'])

In [46]:
model.fit(scaled_X_train, y_train, epochs=10, verbose=2)

Epoch 1/10
35/35 - 1s - loss: 0.6814 - accuracy: 0.4886 - 1s/epoch - 29ms/step
Epoch 2/10
35/35 - 0s - loss: 0.6653 - accuracy: 0.6627 - 65ms/epoch - 2ms/step
Epoch 3/10
35/35 - 0s - loss: 0.6479 - accuracy: 0.6964 - 66ms/epoch - 2ms/step
Epoch 4/10
35/35 - 0s - loss: 0.6330 - accuracy: 0.6974 - 70ms/epoch - 2ms/step
Epoch 5/10
35/35 - 0s - loss: 0.6196 - accuracy: 0.7028 - 77ms/epoch - 2ms/step
Epoch 6/10
35/35 - 0s - loss: 0.6063 - accuracy: 0.7156 - 69ms/epoch - 2ms/step
Epoch 7/10
35/35 - 0s - loss: 0.5928 - accuracy: 0.7247 - 74ms/epoch - 2ms/step
Epoch 8/10
35/35 - 0s - loss: 0.5794 - accuracy: 0.7320 - 69ms/epoch - 2ms/step
Epoch 9/10
35/35 - 0s - loss: 0.5662 - accuracy: 0.7366 - 68ms/epoch - 2ms/step
Epoch 10/10
35/35 - 0s - loss: 0.5533 - accuracy: 0.7420 - 78ms/epoch - 2ms/step


In [47]:
scaled_X_test

array([[0.62098955, 0.75284662, 0.21900753, 0.5730998 ],
       [0.48778602, 0.82175665, 0.09174727, 0.56211079],
       [0.51158363, 0.77924916, 0.13830875, 0.50392598],
       ...,
       [0.75753773, 0.34889447, 0.37966768, 0.81250432],
       [0.48778747, 0.82175665, 0.09174727, 0.56211079],
       [0.70853615, 0.92621058, 0.07349701, 0.38693083]])

In [48]:
model.predict(scaled_X_test)

9/9 [==============================] - 0s 2ms/step


array([[0.33224678],
       [0.3632253 ],
       [0.36756116],
       [0.6838038 ],
       [0.2633124 ],
       [0.23878671],
       [0.4606687 ],
       [0.2063557 ],
       [0.24679485],
       [0.44485015],
       [0.2615538 ],
       [0.34409884],
       [0.5864433 ],
       [0.5742411 ],
       [0.7410789 ],
       [0.2520381 ],
       [0.5356875 ],
       [0.5353093 ],
       [0.811907  ],
       [0.5868068 ],
       [0.26808655],
       [0.40083233],
       [0.5280943 ],
       [0.2374287 ],
       [0.7038113 ],
       [0.23428021],
       [0.27133173],
       [0.57253015],
       [0.2065916 ],
       [0.20869987],
       [0.31706434],
       [0.40536568],
       [0.42352673],
       [0.7347569 ],
       [0.64519215],
       [0.24011432],
       [0.2599538 ],
       [0.31376266],
       [0.37013057],
       [0.3993823 ],
       [0.4887696 ],
       [0.3428362 ],
       [0.33064583],
       [0.27194002],
       [0.56633097],
       [0.70587784],
       [0.49581766],
       [0.267

In [49]:
#model.predict_classes(scaled_X_test)

Evaluating Model

In [50]:
model.metrics_names

['loss', 'accuracy']

In [51]:
model.evaluate(x=scaled_X_test, y=y_test)

9/9 [==============================] - 0s 3ms/step - loss: 0.5833 - accuracy: 0.7345


[0.5833358764648438, 0.7345454692840576]

In [52]:
from sklearn.metrics import confusion_matrix, classification_report

In [54]:
predict_x=model.predict(scaled_X_test) 
classes_x=np.argmax(predict_x,axis=1)

9/9 [==============================] - 0s 3ms/step


In [55]:
classes_x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [57]:
confusion_matrix(y_test, classes_x)

array([[148,   0],
       [127,   0]], dtype=int64)

In [59]:
predictions = (model.predict(scaled_X_test) > 0.5).astype("int32")

9/9 [==============================] - 0s 2ms/step


In [61]:
confusion_matrix(y_test, predictions)

array([[133,  15],
       [ 58,  69]], dtype=int64)

In [62]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         0.0       0.70      0.90      0.78       148
         1.0       0.82      0.54      0.65       127

    accuracy                           0.73       275
   macro avg       0.76      0.72      0.72       275
weighted avg       0.75      0.73      0.72       275



In [63]:
model.save('mydeeplearningmodel')

INFO:tensorflow:Assets written to: mydeeplearningmodel\assets


INFO:tensorflow:Assets written to: mydeeplearningmodel\assets


In [64]:
from keras.models import load_model

In [65]:
newmodel = load_model('mydeeplearningmodel')

In [66]:
newmodel.predict(X_test)

9/9 [==============================] - 0s 3ms/step


array([[3.48742992e-01],
       [1.90175906e-01],
       [2.13085771e-01],
       [9.53356802e-01],
       [1.97661314e-02],
       [7.78619619e-03],
       [8.99593592e-01],
       [9.17947385e-04],
       [1.26485210e-02],
       [9.71387208e-01],
       [1.06357345e-02],
       [1.41917169e-01],
       [9.99594033e-01],
       [9.97553349e-01],
       [9.99969244e-01],
       [3.59855918e-03],
       [9.81907248e-01],
       [9.75609124e-01],
       [9.99999702e-01],
       [9.96200979e-01],
       [3.21757980e-02],
       [9.85890925e-01],
       [9.93792593e-01],
       [4.07684641e-03],
       [9.58086431e-01],
       [7.03116832e-03],
       [1.00278102e-01],
       [9.96856570e-01],
       [3.31199059e-04],
       [1.41827355e-03],
       [9.83189791e-02],
       [9.70257044e-01],
       [9.83788311e-01],
       [9.40621853e-01],
       [6.84985995e-01],
       [8.68706591e-03],
       [9.72967967e-03],
       [1.11422397e-01],
       [2.79218793e-01],
       [9.61452246e-01],
